openapi: 3.0.0
info:
  version: 1.0.0
  title: Personal Blog API
  description: API for Personal Blog
paths:
  /register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: johndoe@example.com
                password:
                  type: string
                  example: password123
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Register successfully
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          name:
                            type: string
                            example: John Doe
                          email:
                            type: string
                            example: johndoe@example.com
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Bad request
                  error:
                    type: string
                    example: Account has been registered.
                  data:
                    type: string
                    nullable: true
                    example: null

  /login:
    post:
      tags:
      - Auth
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: johndoe@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login Successfully
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: John Doe
                      email:
                        type: string
                        example: johndoe@example.com
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Bad request
                  error:
                    type: string
                    example: Invalid Email or Password

# articles
  /articles:
    post:
      tags:
        - Article
      summary: Create a new article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "New Article"
                content:
                  type: string
                  example: "Article content goes here..."
                createdAt:
                  type: string
                  format: date-time
                  example: "2023-07-19T00:00:00Z"
                authorId:
                  type: integer
                  example: 1
      responses:
        '201':
          description: Article created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Article created successfully"
                  data:
                    $ref: '#/components/schemas/Article'
        '400':
          description: Bad request
        '500':
          description: Server error
  /articles/{id}:
    put:
      tags:
        - Article
      summary: Update an existing article
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the article to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Updated Article"
                content:
                  type: string
                  example: "Updated content goes here..."
                updatedAt:
                  type: string
                  format: date-time
                  example: "2023-07-19T00:00:00Z"
                authorId:
                  type: integer
                  example: 1
      responses:
        '201':
          description: Article updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Article is updated!"
                  data:
                    $ref: '#/components/schemas/Article'
        '404':
          description: Article not found
        '500':
          description: Server error
    patch:
      tags:
        - Article
      summary: Update article publish status
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the article to update publish status
      responses:
        '201':
          description: Publish status has been updated!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Publish status has been updated!"
                  data:
                    $ref: '#/components/schemas/Article'
        '404':
          description: Article not found
        '500':
          description: Server error
    delete:
      tags:
        - Article
      summary: Delete an article
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the article to delete
      responses:
        '201':
          description: Article has been deleted!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Article has been deleted!"
                  data:
                    $ref: '#/components/schemas/Article'
        '404':
          description: Article not found
        '500':
          description: Server error
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Article Title"
        content:
          type: string
          example: "Content of the article"
        createdAt:
          type: string
          format: date-time
          example: "2023-07-19T00:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-07-19T00:00:00Z"
        authorId:
          type: integer
          example: 1
        published:
          type: boolean
          example: true
